# Change these first
owner: HeliosCompliance # Your GitHub organization or username, where this repository lives
repo: upptime-orbit # The name of this repository

sites:
  - name: Orbit
    url: https://ctcbanks.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ctcbanks.com
  # baseUrl: /your-repo-name
  logoUrl: /assets/orbit_logo.svg
  name: Orbit Status
  introTitle: "Orbit Status Page"
  introMessage: Live system availability and incident updates for Orbit.
  navbar:
    - title: Status
      href: /
    - title: Incident History
      href: https://github.com/$OWNER/$REPO/issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
